-- -------------------------------------------------------------
-- Nexora DPR Portal Database Schema and Seeding Script
-- Paste this script into your Supabase SQL Editor and run it.
-- -------------------------------------------------------------

-- Drop tables if they exist (for a fresh start if needed)
DROP TABLE IF EXISTS public.notifications;
DROP TABLE IF EXISTS public.announcements;
DROP TABLE IF EXISTS public.reports;
DROP TABLE IF EXISTS public.projects;
DROP TABLE IF EXISTS public.users;

-- 1. Create USERS table
CREATE TABLE public.users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  department TEXT,
  "assignedProjects" TEXT[] DEFAULT '{}',
  avatar TEXT,
  phone TEXT,
  "mustChangePassword" BOOLEAN DEFAULT TRUE
);

-- 2. Create PROJECTS table
CREATE TABLE public.projects (
  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'In Progress',
  lead TEXT,
  description TEXT
);

-- 3. Create REPORTS table
CREATE TABLE public.reports (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL,
  "employeeName" TEXT NOT NULL,
  "employeeId" TEXT NOT NULL,
  "employeeEmail" TEXT NOT NULL,
  "projectName" TEXT NOT NULL,
  "moduleName" TEXT,
  "taskAssigned" TEXT,
  "taskCompletedToday" TEXT,
  "workStatus" TEXT NOT NULL,
  "hoursWorked" NUMERIC DEFAULT 0,
  "percentageCompleted" INTEGER DEFAULT 0,
  "challengesFaced" TEXT,
  "tomorrowPlan" TEXT,
  images TEXT[] DEFAULT '{}',
  files JSONB DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'Pending',
  feedback TEXT,
  "approvedBy" TEXT,
  "approvedAt" TEXT
);

-- 4. Create ANNOUNCEMENTS table
CREATE TABLE public.announcements (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  date TEXT NOT NULL,
  sender TEXT NOT NULL
);

-- 5. Create NOTIFICATIONS table
CREATE TABLE public.notifications (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  date TEXT NOT NULL,
  read BOOLEAN DEFAULT FALSE
);

-- -------------------------------------------------------------
-- Enable RLS & Configure Permissive Client-Side Access Policies
-- -------------------------------------------------------------

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all operations for users" ON public.users FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for projects" ON public.projects FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for reports" ON public.reports FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for announcements" ON public.announcements FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Enable all operations for notifications" ON public.notifications FOR ALL TO public USING (true) WITH CHECK (true);

-- -------------------------------------------------------------
-- Seed Data Insertion
-- -------------------------------------------------------------

-- Seed users
INSERT INTO public.users (id, name, email, password, role, department, "assignedProjects", avatar, phone, "mustChangePassword")
VALUES
('EMP-001', 'Trivin', 'trivin@nexora.com', '123456', 'admin', 'Management', '{"All"}', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150', '+1 (555) 019-2834', true),
('EMP-002', 'Aakashraj', 'aakashraj@nexora.com', '123456', 'member', 'Engineering', '{"Nexora ERP", "CloudSync"}', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', '+1 (555) 019-5829', true),
('EMP-003', 'Gopika', 'gopika@nexora.com', '123456', 'member', 'Design', '{"CyberShield"}', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', '+1 (555) 019-9481', true),
('EMP-004', 'Akshaya', 'akshaya@nexora.com', '123456', 'member', 'Engineering', '{"AI Analyst"}', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150', '+1 (555) 019-3382', true),
('EMP-005', 'Amirtha', 'amirtha@nexora.com', '123456', 'member', 'Engineering', '{"Nexora ERP"}', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', '+1 (555) 019-7482', true),
('EMP-006', 'Pavithraa', 'pavithraa@nexora.com', '123456', 'member', 'Quality Assurance', '{"CloudSync"}', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150', '+1 (555) 019-2910', true),
('EMP-007', 'Sujitha', 'sujitha@nexora.com', '123456', 'member', 'Engineering', '{"CyberShield"}', 'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=150', '+1 (555) 019-8739', true),
('EMP-008', 'Sangamithra', 'sangamithra@nexora.com', '123456', 'member', 'Design', '{"AI Analyst"}', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150', '+1 (555) 019-1144', true),
('EMP-009', 'VishnuHasan', 'vishnuhasan@nexora.com', '123456', 'member', 'Engineering', '{"Nexora ERP", "CyberShield"}', 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150', '+1 (555) 019-8239', true),
('EMP-010', 'Aaryan', 'aaryan@nexora.com', '123456', 'member', 'Engineering', '{"CloudSync"}', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150', '+1 (555) 019-7431', true),
('EMP-011', 'Ajaykumar', 'ajaykumar@nexora.com', '123456', 'member', 'Quality Assurance', '{"AI Analyst"}', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150', '+1 (555) 019-8120', true),
('EMP-012', 'Pathmavathi', 'pathmavathi@nexora.com', '123456', 'member', 'Management', '{"Nexora ERP"}', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150', '+1 (555) 019-1229', true),
('EMP-013', 'Pooja', 'pooja@nexora.com', '123456', 'member', 'Design', '{"CyberShield"}', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150', '+1 (555) 019-4820', true),
('EMP-014', 'Aarathana', 'aarathana@nexora.com', '123456', 'member', 'Engineering', '{"CloudSync"}', 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150', '+1 (555) 019-3349', true),
('EMP-015', 'Gokulashri', 'gokulashri@nexora.com', '123456', 'member', 'Engineering', '{"AI Analyst"}', 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=150', '+1 (555) 019-2283', true),
('EMP-016', 'Karthikeyan', 'karthikeyan@nexora.com', '123456', 'member', 'Engineering', '{"Nexora ERP", "CloudSync"}', 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150', '+1 (555) 019-2248', true),
('EMP-017', 'Logesh', 'logesh@nexora.com', '123456', 'member', 'Quality Assurance', '{"CyberShield"}', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150', '+1 (555) 019-1182', true),
('EMP-018', 'Sanjay Kumar', 'sanjaykumar@nexora.com', '123456', 'member', 'Engineering', '{"AI Analyst"}', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150', '+1 (555) 019-9944', true),
('EMP-019', 'Sanjay', 'sanjay@nexora.com', '123456', 'member', 'Design', '{"Nexora ERP"}', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150', '+1 (555) 019-8812', true),
('EMP-020', 'Vishwa', 'vishwa@nexora.com', '123456', 'member', 'Engineering', '{"CloudSync"}', 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=150', '+1 (555) 019-4821', true),
('EMP-021', 'Shakthi', 'shakthi@nexora.com', '123456', 'member', 'Engineering', '{"CyberShield", "AI Analyst"}', 'https://images.unsplash.com/photo-1601412436009-d964bd02edbc?w=150', '+1 (555) 019-4810', true),
('EMP-022', 'Farman', 'farman@nexora.com', '123456', 'member', 'Engineering', '{"Nexora ERP"}', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150', '+1 (555) 019-9182', true),
('EMP-023', 'Gokul', 'gokul@nexora.com', '123456', 'member', 'Engineering', '{"CloudSync"}', 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150', '+1 (555) 019-8139', true);

-- Seed projects
INSERT INTO public.projects (id, name, status, lead, description)
VALUES
('PROJ-01', 'Nexora ERP', 'In Progress', 'Trivin', 'Core enterprise resource planning platform.'),
('PROJ-02', 'CloudSync', 'In Progress', 'Aakashraj', 'Real-time file synchronization and backup.'),
('PROJ-03', 'CyberShield', 'In Progress', 'Gopika', 'Cloud infrastructure security compliance suite.'),
('PROJ-04', 'AI Analyst', 'Planning', 'Akshaya', 'Generative AI reporting dashboard integration.');

-- Seed reports (using dynamic PostgreSQL relative dates)
INSERT INTO public.reports (id, date, "employeeName", "employeeId", "employeeEmail", "projectName", "moduleName", "taskAssigned", "taskCompletedToday", "workStatus", "hoursWorked", "percentageCompleted", "challengesFaced", "tomorrowPlan", images, files, status, feedback, "approvedBy", "approvedAt")
VALUES
('REP-1001', to_char(CURRENT_DATE - INTERVAL '6 days', 'YYYY-MM-DD'), 'Aakashraj', 'EMP-002', 'aakashraj@nexora.com', 'Nexora ERP', 'Authentication', 'Integrate JWT token verify middleware', 'Successfully wrote express middleware, unit tested token validation flow, and added refresh token logic.', 'Completed', 8, 100, 'None', 'Start setting up route authorization for admin endpoints.', '{"https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400"}', '[{"name": "jwt-middleware-spec.pdf", "size": "482 KB"}]'::jsonb, 'Approved', 'Excellent work on the verification middleware, Aakashraj! Keep it up.', 'Trivin', to_char(CURRENT_DATE - INTERVAL '5 days', 'YYYY-MM-DD')),

('REP-1002', to_char(CURRENT_DATE - INTERVAL '6 days', 'YYYY-MM-DD'), 'Gopika', 'EMP-003', 'gopika@nexora.com', 'CyberShield', 'Dashboard UX', 'Design high-fidelity mockups for threat detector list', 'Created Figma mockups for real-time alert grid, filtering bar, and detail sidebar panels.', 'Completed', 7.5, 100, 'Aligning on colors with branding guidelines.', 'Begin prototyping alert animations in Tailwind.', '{"https://images.unsplash.com/photo-1541462608143-67571c6738dd?w=400"}', '[{"name": "FigmaExport_ThreatsGrid.zip", "size": "4.2 MB"}]'::jsonb, 'Approved', 'Great UI colors. Make sure to double-check color contrast rules.', 'Trivin', to_char(CURRENT_DATE - INTERVAL '5 days', 'YYYY-MM-DD')),

('REP-1003', to_char(CURRENT_DATE - INTERVAL '5 days', 'YYYY-MM-DD'), 'Aakashraj', 'EMP-002', 'aakashraj@nexora.com', 'Nexora ERP', 'Authentication', 'Set up route authorization for admin endpoints', 'Implemented custom RBAC checks on API routes. Configured mock roles for local setup validation.', 'Completed', 8, 100, 'Nested roles config took longer than expected.', 'Migrate database seeding scripts.', '{}', '[]'::jsonb, 'Approved', 'Approved.', 'Trivin', to_char(CURRENT_DATE - INTERVAL '4 days', 'YYYY-MM-DD')),

('REP-1004', to_char(CURRENT_DATE - INTERVAL '5 days', 'YYYY-MM-DD'), 'Akshaya', 'EMP-004', 'akshaya@nexora.com', 'Nexora ERP', 'Core Reporting API', 'Design endpoints for report aggregations', 'Created aggregation pipes for daily stats, completed vs blocked statistics.', 'In Progress', 8, 60, 'Memory leak in aggregations queries due to non-indexed fields in testing database.', 'Add indices and finalize the controller logic.', '{}', '[]'::jsonb, 'Approved', 'Make sure you create indexes for both employeeId and date.', 'Trivin', to_char(CURRENT_DATE - INTERVAL '4 days', 'YYYY-MM-DD')),

('REP-1005', to_char(CURRENT_DATE - INTERVAL '4 days', 'YYYY-MM-DD'), 'Gopika', 'EMP-003', 'gopika@nexora.com', 'CyberShield', 'Dashboard UX', 'Begin prototyping alert animations in Tailwind', 'Wrote Tailwind transitions for active alarm states and expand-collapse transitions.', 'Completed', 6, 100, 'None', 'Review prototypes with engineering lead to ensure performance.', '{"https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=400"}', '[]'::jsonb, 'Approved', 'Smooth animations, tested locally and it looks fantastic.', 'Trivin', to_char(CURRENT_DATE - INTERVAL '3 days', 'YYYY-MM-DD')),

('REP-1006', to_char(CURRENT_DATE - INTERVAL '4 days', 'YYYY-MM-DD'), 'Aakashraj', 'EMP-002', 'aakashraj@nexora.com', 'CloudSync', 'Delta Uploads', 'Research Rsync style chunk hash algorithms for client syncing', 'Read papers on rolling hash functions. Set up initial benchmark tests for md5 vs adler32.', 'In Progress', 8, 40, 'Adler32 has collision weaknesses but is significantly faster in client-side JS runtimes.', 'Test performance on files over 1GB.', '{}', '[{"name": "rolling-hash-benchmarks.xlsx", "size": "112 KB"}]'::jsonb, 'Approved', 'Very thorough research. Go with Adler32 for now.', 'Trivin', to_char(CURRENT_DATE - INTERVAL '3 days', 'YYYY-MM-DD')),

('REP-1014', to_char(CURRENT_DATE, 'YYYY-MM-DD'), 'Aakashraj', 'EMP-002', 'aakashraj@nexora.com', 'Nexora ERP', 'Dashboard Integration', 'Solve overlay stacking context and submit', 'Fixed z-index stacking layers by wrapping popovers in portals. Added micro-animations to calendar dots.', 'Completed', 8, 100, 'None', 'Support custom range selections on filters.', '{}', '[]'::jsonb, 'Pending', '', '', '');

-- Seed announcements
INSERT INTO public.announcements (title, content, date, sender)
VALUES
('Q2 Core Performance Reviews', 'All departments are scheduled to submit final Q2 milestones before next Friday. Please sync with your direct managers for specific checklist templates.', to_char(CURRENT_DATE - INTERVAL '1 day', 'YYYY-MM-DD'), 'Trivin'),
('Vite and Tailwind Upgrades', 'We have upgraded our workspace dependencies to support faster HMR and optimized styles bundle sizes.', to_char(CURRENT_DATE - INTERVAL '3 days', 'YYYY-MM-DD'), 'System Administrator');

-- Seed notifications
INSERT INTO public.notifications (id, "userId", type, title, message, date, read)
VALUES
('NOT-01', 'EMP-002', 'status_update', 'Report Approved', 'Trivin approved your report for [Delta Uploads].', to_char(CURRENT_DATE - INTERVAL '1 day', 'YYYY-MM-DDTHH24:MI:SSZ'), false),
('NOT-02', 'EMP-003', 'status_update', 'Report Approved', 'Trivin approved your report for [Prompt Templates].', to_char(CURRENT_DATE, 'YYYY-MM-DDTHH24:MI:SSZ'), false);
